### ISSUE TITLE
Not working with Python 3.8.x

### ISSUE THREAD

**Issue by infeeeee** [abcminiuser/mpc-hc-webui-proxy#2]
Not working with python 3.8.x, I think because of this bug: 

https://github.com/aio-libs/aiohttp/issues/3644

Tried with 3.8.3 and 3.8.4rc1, same results. 
Tried installing python to Program Files and Appdata, same results.
Win10 1909, downloaded python from python.org.

I worked around the issue, by installing Python 3.7.8, everything working as expected. 

Here is the log with 3.8.4rc1:

```
E:\_PortableApps\mpc-hc-webui-proxy>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting aiohttp==3.5.4
  Downloading aiohttp-3.5.4.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.4.2-cp38-cp38-win_amd64.whl (126 kB)
     |████████████████████████████████| 126 kB 3.3 MB/s
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting attrs>=17.3.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting multidict<5.0,>=4.0
  Downloading multidict-4.7.6-cp38-cp38-win_amd64.whl (48 kB)
     |████████████████████████████████| 48 kB 2.5 MB/s
Collecting chardet<4.0,>=2.0
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB ...
Collecting idna>=2.0
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Building wheels for collected packages: aiohttp
  Building wheel for aiohttp (PEP 517) ... done
  Created wheel for aiohttp: filename=aiohttp-3.5.4-py3-none-any.whl size=433145 sha256=49197b5684093804872747ad9d211625ac2a4ea372ec402f2c301e744d1a3af3
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\89\84\e6\de199bc435ee4eb6a0d978d3b59457fd05ac67ab1bc4e66e11
Successfully built aiohttp
Installing collected packages: idna, multidict, yarl, async-timeout, attrs, chardet, aiohttp
  WARNING: The script chardetect.exe is installed in 'C:\Users\user\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed aiohttp-3.5.4 async-timeout-3.0.1 attrs-19.3.0 chardet-3.0.4 idna-2.10 multidict-4.7.6 yarl-1.4.2

E:\_PortableApps\mpc-hc-webui-proxy>python mpc-hc-proxy.py
======== Running on http://0.0.0.0:13579 ========
(Press CTRL+C to quit)
2020-07-12 21:34:55,145 ERROR asyncio Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...139', 44322))>) at C:\Program Files\Python38\lib\asyncio\proactor_events.py:798
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...139', 44322))>) at C:\Program Files\Python38\lib\asyncio\proactor_events.py:798>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 805, in loop
    protocol = protocol_factory()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\aiohttp\web_server.py", line 57, in __call__
    return RequestHandler(self, loop=self._loop, **self._kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\aiohttp\web_protocol.py", line 136, in __init__
    self._keepalive = False
AttributeError: 'RequestHandler' object has no attribute '_keepalive'
```

**Comment by abcminiuser** [comment]
I just tried it with my local Python 3.8.2 and it worked fine, although I was using a newer version of `aiohttp` locally. I've updated the `requirements.txt` to bump the dependency to the latest version, which should fix it.

Please try with `aiohttp` 3.6.2 and the latest Python and let me know if it works for you like it does for me.

**Comment by infeeeee** [comment]
Yes, it works this way with 3.8.4!

Thank you for your help!
